version: '3.7'

services:

  fpm:
    container_name: news_fpm
    build: docker/fpm
    env_file:
      - ./.env
    volumes:
      - ./app:/application

  nginx:
    container_name: news_nginx
    image: nginx:1.19.0-alpine
    expose:
      - "80"
    ports:
      - "80:80"
#    user: "www-data"
    volumes:
      - ./app:/application
      - ./docker/nginx:/etc/nginx

  mysql:
    container_name: news_mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - ${DB_OUT_PORT}:3306

  memcached:
    container_name: news_memcached
    image: memcached:alpine

